[package]
name = "cftool"
version = "0.1.1"
authors = ["Xi Ruoyao <xry111@mengyan1223.wang>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = "0.9.20"
regex = "1"
clap = "2.33"
directories = "2.0"
log = "0.4"
stderrlog = "0.4"
serde_json = "1.0"
rpassword = "4.0"
url = "2.1.0"
termcolor = "1"
error-chain = "0.12.1"
cookie_store = "0.9.0"
